* Introduction
Run postgis on kubernetes. Warning: Very opinionated setup we use for our services.

- Postgres setup is based on mix of https://github.com/docker-library/postgres and https://github.com/appropriate/docker-postgis .
- Kubernetes setup is using the helm chart: https://github.com/kubernetes/charts/tree/master/stable/postgresql

Also includes tiny extension uuid-ossp we use (see why: https://www.starkandwayne.com/blog/uuid-primary-keys-in-postgresql/).
* Pre-requsities
- Python fabric (pip2 install fabric)
- Kubernetes helm (kubernetes-helm in arch-linux AUR)
* Installation
** Update constants
Update constants in =fabfile.py=
** Push image
=fab push_image=
** Connect to your kubernetes cluster
#+BEGIN_SRC bash :results output
  gcloud container clusters get-credentials your-cluster-name
#+END_SRC
** Create and configure database
=fab setup_db=
* Maintenance
** Start postgress shell
=fab postgres_shell=
** SQL alchemy connection string
Password is different on each cluster, so do not hardcode it.

=fab print_alchemy_connection_string=
** Delete database
Be careful to not do it on prod.
#+BEGIN_SRC bash :results output
  export CHART_NAME=tensorflight-postgres
  helm delete --purge $CHART_NAME
#+END_SRC
